package(default_visibility = ["//visibility:public"])

load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "itertools",
    srcs = [
        "lib.rs",
    ],
    deps = [
        "//util/primitive",
    ],
)
