package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_rust//rust:rust.bzl", "rust_library")

rust_library(
    name = "flags",
    srcs = [
        "lib.rs",
        "parse.rs",
    ],
)
