package(default_visibility = ["//visibility:public"])

load("//tools/fec:fec.bzl", "fe_library")

fe_library(
    name = "store",
    srcs = ["store.mjs"],
)

fe_library(
    name = "debounce",
    srcs = ["debounce.mjs"],
)
